name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'posts/**'
      - 'comments/**'
      - 'query/**'
      - 'moderation/**'
      - 'event-bus/**'
      - 'client/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'posts/**'
      - 'comments/**'
      - 'query/**'
      - 'moderation/**'
      - 'event-bus/**'
      - 'client/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Check for changes
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          posts:
            - 'posts/**'
          comments:
            - 'comments/**'
          query:
            - 'query/**'
          moderation:
            - 'moderation/**'
          event-bus:
            - 'event-bus/**'
          client:
            - 'client/**'
            
    - name: Build and push posts service
      if: steps.changes.outputs.posts == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./posts
        push: true
        tags: rarias1082/blog-posts:latest
        
    - name: Build and push comments service
      if: steps.changes.outputs.comments == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./comments
        push: true
        tags: rarias1082/blog-comments:latest
        
    - name: Build and push query service
      if: steps.changes.outputs.query == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./query
        push: true
        tags: rarias1082/blog-query:latest
        
    - name: Build and push moderation service
      if: steps.changes.outputs.moderation == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./moderation
        push: true
        tags: rarias1082/blog-moderation:latest
        
    - name: Build and push event-bus service
      if: steps.changes.outputs.event-bus == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./event-bus
        push: true
        tags: rarias1082/blog-event-bus:latest
        
    - name: Build and push client service
      if: steps.changes.outputs.client == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./client
        push: true
        tags: rarias1082/blog-client:latest