name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'posts/**'
      - 'comments/**'
      - 'query/**'
      - 'moderation/**'
      - 'event-bus/**'
      - 'client/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'posts/**'
      - 'comments/**'
      - 'query/**'
      - 'moderation/**'
      - 'event-bus/**'
      - 'client/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Check posts changes
      uses: dorny/paths-filter@v2
      id: posts-changes
      with:
        filters: |
          posts:
            - 'posts/**'
            
    - name: Build and push posts service
      if: steps.posts-changes.outputs.posts == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./posts
        push: true
        tags: rarias1082/blog-posts:latest
        
    - name: Check comments changes
      uses: dorny/paths-filter@v2
      id: comments-changes
      with:
        filters: |
          comments:
            - 'comments/**'
            
    - name: Build and push comments service
      if: steps.comments-changes.outputs.comments == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./comments
        push: true
        tags: rarias1082/blog-comments:latest
        
    - name: Check query changes
      uses: dorny/paths-filter@v2
      id: query-changes
      with:
        filters: |
          query:
            - 'query/**'
            
    - name: Build and push query service
      if: steps.query-changes.outputs.query == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./query
        push: true
        tags: rarias1082/blog-query:latest
        
    - name: Check moderation changes
      uses: dorny/paths-filter@v2
      id: moderation-changes
      with:
        filters: |
          moderation:
            - 'moderation/**'
            
    - name: Build and push moderation service
      if: steps.moderation-changes.outputs.moderation == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./moderation
        push: true
        tags: rarias1082/blog-moderation:latest
        
    - name: Check event-bus changes
      uses: dorny/paths-filter@v2
      id: event-bus-changes
      with:
        filters: |
          event-bus:
            - 'event-bus/**'
            
    - name: Build and push event-bus service
      if: steps.event-bus-changes.outputs.event-bus == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./event-bus
        push: true
        tags: rarias1082/blog-event-bus:latest
        
    - name: Check client changes
      uses: dorny/paths-filter@v2
      id: client-changes
      with:
        filters: |
          client:
            - 'client/**'
            
    - name: Build and push client service
      if: steps.client-changes.outputs.client == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./client
        push: true
        tags: rarias1082/blog-client:latest